// *** WARNING: this file was generated by pulumi-gen-short-io. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export * from "./provider";

// Export sub-modules:
import * as pulumi-short-io from "./pulumi-short-io";

export {
    pulumi-short-io,
};

import { Provider } from "./provider";

pulumi.runtime.registerResourcePackage("short-io", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:short-io") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
