// *** WARNING: this file was generated by pulumi-gen-short-io. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Link extends pulumi.CustomResource {
    /**
     * Get an existing Link resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Link {
        return new Link(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'short-io:index:Link';

    /**
     * Returns true if the given object is an instance of Link.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Link {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Link.__pulumiType;
    }

    public readonly domain!: pulumi.Output<string>;
    public /*out*/ readonly idString!: pulumi.Output<string>;
    public readonly long!: pulumi.Output<string>;
    public readonly short!: pulumi.Output<string>;

    /**
     * Create a Link resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: LinkArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.domain === undefined) && !opts.urn) {
                throw new Error("Missing required property 'domain'");
            }
            if ((!args || args.long === undefined) && !opts.urn) {
                throw new Error("Missing required property 'long'");
            }
            if ((!args || args.short === undefined) && !opts.urn) {
                throw new Error("Missing required property 'short'");
            }
            resourceInputs["domain"] = args ? args.domain : undefined;
            resourceInputs["long"] = args ? args.long : undefined;
            resourceInputs["short"] = args ? args.short : undefined;
            resourceInputs["idString"] = undefined /*out*/;
        } else {
            resourceInputs["domain"] = undefined /*out*/;
            resourceInputs["idString"] = undefined /*out*/;
            resourceInputs["long"] = undefined /*out*/;
            resourceInputs["short"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Link.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Link resource.
 */
export interface LinkArgs {
    domain: pulumi.Input<string>;
    long: pulumi.Input<string>;
    short: pulumi.Input<string>;
}
